// Backwards-compatible export layer for CatalogAdmin
// All implementation details are decomposed under `./admin/`

export {
  AdminShell as default,
  AdminShell as CatalogAdmin,
  ProductEditor,
  LogManager,
  AnalyticsSection,
  ProductsSection,
  BrandsSection,
  CategoriesSection,
  MediaSection,
  SnapshotsSection,
  LogsSection,
  AppearanceManager,
  ArticleManager,
  ContactManager,
  SecurityManager,
  isProductModified,
  slugify,
  newId,
  emptyProduct,
  getProductUniqueMediaUrls,
  getProductUniqueMediaCount,
  getProductVideoCount,
  getProductImageCount,
  PRESET_COLORS,
} from './admin';

export type {
  AdminShellProps as Props,
  AdminShellProps,
  Tab,
  ProductEditorProps,
  LogManagerProps,
  AnalyticsSectionProps,
  ProductsSectionProps,
  BrandsSectionProps,
  CategoriesSectionProps,
  MediaSectionProps,
  SnapshotsSectionProps,
  LogsSectionProps,
  AppearanceManagerProps,
  ArticleManagerProps,
  ContactManagerProps,
  SecurityManagerProps,
  CompletenessFilter,
} from './admin';
